"""Add6 Column tags in Place

Revision ID: 02cf77cbe471
Revises: 21edfb33ff21
Create Date: 2023-04-24 22:04:29.661084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cf77cbe471'
down_revision = '21edfb33ff21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
