"""Add Column photo User

Revision ID: 143554072515
Revises: 24b9763887ee
Create Date: 2023-04-21 11:21:53.592904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143554072515'
down_revision = '24b9763887ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_user')
    # ### end Alembic commands ###
