"""Add5 Column tags in Place

Revision ID: 21edfb33ff21
Revises: 4f426ce5bdd9
Create Date: 2023-04-24 22:00:32.456158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21edfb33ff21'
down_revision = '4f426ce5bdd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
