"""add relationship2

Revision ID: 3cb8b139a268
Revises: b08b4b191caf
Create Date: 2023-05-27 18:18:10.954779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb8b139a268'
down_revision = 'b08b4b191caf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
