"""Add4 Column tags in Place

Revision ID: 4f426ce5bdd9
Revises: b897f7fdebe3
Create Date: 2023-04-24 21:49:10.336764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f426ce5bdd9'
down_revision = 'b897f7fdebe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
