"""Add2 Column tags in Place

Revision ID: 519ef49d6179
Revises: bea7167570e3
Create Date: 2023-04-24 21:29:10.950760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519ef49d6179'
down_revision = 'bea7167570e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'tags')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('place', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
