"""Add8 Column tags in Place

Revision ID: 6d8e2427e08b
Revises: ebc988e4751d
Create Date: 2023-04-24 22:47:19.070214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8e2427e08b'
down_revision = 'ebc988e4751d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('placetags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('placetags', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placetags', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('placetags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
