"""add rating in Place

Revision ID: 83a630ee60a5
Revises: 7b2177edc133
Create Date: 2023-05-18 16:51:23.948507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a630ee60a5'
down_revision = '7b2177edc133'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'rating')
    # ### end Alembic commands ###
