"""add relationship

Revision ID: b08b4b191caf
Revises: 83a630ee60a5
Create Date: 2023-05-27 18:05:44.458118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08b4b191caf'
down_revision = '83a630ee60a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
