"""Add3 Column tags in Place

Revision ID: b897f7fdebe3
Revises: 519ef49d6179
Create Date: 2023-04-24 21:43:21.456408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b897f7fdebe3'
down_revision = '519ef49d6179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
