"""Add Column tags in Place

Revision ID: bea7167570e3
Revises: 6ac5c823ec01
Create Date: 2023-04-24 20:37:32.156288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea7167570e3'
down_revision = '6ac5c823ec01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'tags')
    # ### end Alembic commands ###
