"""Add7 Column tags in Place

Revision ID: ebc988e4751d
Revises: 02cf77cbe471
Create Date: 2023-04-24 22:08:52.160283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc988e4751d'
down_revision = '02cf77cbe471'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
